version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forge
      MYSQL_USER: forge
      MYSQL_PASSWORD: forge
    ports:
      - "11002:3306"
    volumes:
      - dbfile_local:/var/lib/mysql

  php-fpm:
    build:
      context: .
      dockerfile: ./phpdocker/php/Dockerfile
    container_name: php_local
    working_dir: /application
    volumes:
      - ./:/application # весь проект
      - vendor_local:/application/vendor
      - bootstrap_cache_local:/application/bootstrap/cache
      - ./phpdocker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql

  webserver:
    image: nginx:alpine
    container_name: nginx_local
    depends_on:
      - php-fpm
    volumes:
      - ./:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "11000:80"

  node:
    image: node:20-alpine
    container_name: node_local
    working_dir: /application
    volumes:
      - ./:/application
      - /application/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - php-fpm
    environment:
      - VITE_APP_URL=http://localhost:11000

volumes:
  dbfile_local:
  vendor_local:
  bootstrap_cache_local:
