services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

  app:
    build:
      context: .
      dockerfile: phpdocker/php/Dockerfile
    container_name: app
    working_dir: /application
    volumes:
      - ./public:/application
    depends_on:
      - db
      - redis
    restart: always

  queue:
    build:
      context: .
      dockerfile: phpdocker/php/Dockerfile
    container_name: queue
    command: php artisan queue:work --tries=3 --sleep=3
    depends_on:
      - db
      - redis
    restart: always
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - dbfile:/var/lib/mysql
    environment:
      MYSQL_DATABASE: forge
      MYSQL_USER: forge
      MYSQL_PASSWORD: forge
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - app-network

volumes:
  dbfile:

networks:
  app-network:
    driver: bridge
