version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: ./phpdocker/php
    container_name: app
    working_dir: /application
    volumes:
      - ./:/application
      - ./phpdocker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file:
      - .env.production
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - dbfile:/var/lib/mysql
    environment:
      MYSQL_DATABASE: forge
      MYSQL_USER: forge
      MYSQL_PASSWORD: forge
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine
    container_name: redis

  queue:
    build: ./phpdocker/php
    container_name: queue
    working_dir: /application
    volumes:
      - ./:/application
    command: php artisan queue:work --tries=3
    env_file:
      - .env.production
    depends_on:
      - db
      - redis

volumes:
  dbfile:
