services:
    mysql:
        image: 'mysql:8.0'
        container_name: 'mysql-80'
        working_dir: /application
        volumes:
            - dbfile:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=forge
            - MYSQL_USER=forge
            - MYSQL_PASSWORD=forge
        ports:
            - '11002:3306'

    webserver:
        image: 'nginx:alpine'
        container_name: 'nginx'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '11000:80'

    php-fpm:
        container_name: 'php-fpm'
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
    
    node:
        image: 'node:20'
        container_name: 'node'
        working_dir: /application/public
        volumes:
            - './public:/application/public'
            - '/application/public/node_modules' 
        ports:
            - '5173:5173'
        command: ['tail', '-f', '/dev/null']
volumes:
    dbfile: